package integration_probe

import "core:encoding/json"
import "core:fmt"
import "core:os"
import "core:path/filepath"
import "core:strings"
import "core:testing"

import "../../probe"

run :: proc(
	p: ^probe.Probe,
	name: string,
	expected_exit: int,
	args: []string = nil,
	compiler := "",
) -> probe.Report {
	cmd := make([dynamic]string)
	append(&cmd, "check", "--json")
	append(&cmd, ..args)
	stdout, _ := probe.run_cli(p, name, expected_exit, cmd[:], compiler)
	r: probe.Report
	jerr := json.unmarshal_string(stdout, &r)
	probe.expect(
		p,
		jerr == nil && r.coverage.source_scope != "",
		fmt.tprintf("%s: valid JSON with coverage", name),
	)
	return r
}

has_status :: proc(r: probe.Report, status: string) -> bool {
	for check in r.coverage.checks {if check.status == status {return true}}
	return false
}

command :: proc(args: ..string) {
	state, stdout, stderr, err := os.process_exec({command = args}, context.allocator)
	if err != nil ||
	   state.exit_code != 0 {panic(fmt.tprintf("%v: %v\n%s\n%s", args, err, stdout, stderr))}
}

// Freshly build odx, then run this file from the repository root with ODX_ODIN set.
@(test)
test_evidence :: proc(t: ^testing.T) {
	context.allocator = context.temp_allocator
	defer free_all(context.temp_allocator)
	odin := os.get_env("ODX_ODIN", context.allocator)
	if odin == "" ||
	   !filepath.is_abs(odin) {panic("set ODX_ODIN to the reference compiler's absolute path")}
	bin, berr := filepath.abs("build/odx")
	if berr != nil {panic(fmt.tprintf("%v", berr))}
	root, terr := os.make_directory_temp("", "odx-evidence-*", context.allocator)
	if terr != nil {panic(fmt.tprintf("%v", terr))}
	defer os.remove_all(root)
	p := probe.Probe {
		t    = t,
		bin  = bin,
		root = root,
	}
	config :: `{
 version: 1, roles: {},
 exclude: ["excluded/**", ".odx/**"],
 odin: {flags: [], explicit_allocators: "off"},
}`
	config_path := fmt.tprintf("%s/odx.json5", root)
	probe.write(config_path, config)
	source := fmt.tprintf("%s/lib/lib.odin", root)
	probe.write(source, "package lib\nanswer :: 42\n")
	r := run(&p, "full clean", 0)
	probe.expect(&p, r.coverage.complete && has_status(r, "complete"), "full clean: completed evidence")
	platform := "windows" if ODIN_OS != .Windows else "linux"
	platform_file := fmt.tprintf("lib/inactive_%s.odin", platform)
	probe.write(
		fmt.tprintf("%s/%s", root, platform_file),
		"package lib\nplatform_value :: undeclared_on_active_target\n",
	)
	probe.write(
		fmt.tprintf("%s/lib/generated.odin", root),
		"// Code generated by the evidence probe. DO NOT EDIT.\npackage lib\ngenerated_value :: 7\n",
	)
	probe.write(
		fmt.tprintf("%s/lib/example_test.odin", root),
		"package lib\nimport \"core:testing\"\n@(test)\nexample :: proc(t: ^testing.T) {}\n",
	)
	probe.write(
		fmt.tprintf("%s/lib/conditional.odin", root),
		"package lib\nwhen false { inactive_value :: undeclared_in_inactive_branch }\n",
	)
	probe.write(fmt.tprintf("%s/excluded/broken/bad.odin", root), "not valid Odin\n")
	r = run(&p, "source coverage", 0)
	files := make(map[string]bool)
	for pkg in r.coverage.packages {for file in pkg.files {files[file] = true}}
	probe.expect(
		&p,
		r.coverage.complete && len(r.coverage.packages) == 1 && len(files) == 5,
		"source coverage: only included package files",
	)
	for file in ([]string{platform_file, "lib/generated.odin", "lib/example_test.odin", "lib/conditional.odin"}) {
		probe.expect(&p, files[file], fmt.tprintf("source coverage includes %s", file))
	}
	r = run(&p, "fast", 0, {"--fast"})
	probe.expect(
		&p,
		!r.coverage.complete && has_status(r, "skipped"),
		"fast: compiler evidence explicitly skipped",
	)
	probe.write(source, "answer :: 42\n")
	r = run(&p, "missing package", 1)
	probe.expect(
		&p,
		!r.coverage.complete && len(r.violations) > 0,
		"missing package: diagnostic and incomplete coverage",
	)
	probe.write(
		config_path,
		`{
 version: 1, roles: {},
 exclude: ["excluded/**", ".odx/**"],
 odin: {flags: [], explicit_allocators: "off", allowed_vet_disables: ["unused"]},
}`,
	)
	probe.write(source, "#+vet !unused\npackage lib\nbroken :: proc(\n")
	r = run(&p, "malformed source with allowed vet disable", 1)
	stale := false
	for violation in r.violations {stale ||= violation.rule == "odx/stale-config-entry"}
	probe.expect(
		&p,
		!r.coverage.complete && !stale,
		"failed syntax does not falsely report vet allowance as stale",
	)
	probe.write(config_path, config)
	probe.write(source, "package lib\nanswer: int = \"wrong type\"\n")
	r = run(&p, "compiler source error", 1)
	probe.expect(
		&p,
		!r.coverage.complete && has_status(r, "failed") && len(r.violations) > 0,
		"compiler source error: failed evidence and diagnostics",
	)
	probe.write(source, "package lib\nanswer :: 42\n")

	when ODIN_OS != .Windows {
		fake := fmt.tprintf("%s/fake-odin", root)
		probe.write(fake, "#!/bin/sh\nexit 0\n")
		if err := os.chmod(fake, os.Permissions{.Read_User, .Write_User, .Execute_User});
		   err != nil {panic(fmt.tprintf("%v", err))}
		// Exported-procedure checks demand doc evidence even when this example has no violations.
		probe.write(
			fmt.tprintf("%s/.odx/topics/probe/topic.md", root),
			`---
name: "probe",
summary: "Compiler evidence probe",
---
Probe.
`,
		)
		probe.write(
			fmt.tprintf("%s/.odx/topics/probe/R1.odx.md", root),
			`---
id: "R1",
statement: "Fallible exported procedures require results",
why: "Do not silently discard failure",
instead_of: "Discarding failures",
evidence: "Compiler entity facts",
cost: "Compiler doc",
severity: "error",
check: {kind: "require_attribute", attribute: "require_results", on: "exported_procs"},
---
Probe.
`,
		)
		r = run(&p, "success without doc output", 2, compiler = fake)
		probe.expect(
			&p,
			!r.coverage.complete && has_status(r, "failed") && len(r.tool_errors) > 0,
			"missing doc output: unavailable evidence",
		)
		probe.write(fake, "#!/bin/sh\nif [ \"$1\" = doc ]; then exit 7; fi\nexit 0\n")
		r = run(&p, "doc process failure", 2, compiler = fake)
		probe.expect(
			&p,
			!r.coverage.complete && has_status(r, "failed"),
			"doc process failure: failed evidence",
		)
		probe.write(
			fake,
			`#!/bin/sh
echo '{"error_count":1,"errors":[{"type":"warning","pos":null,"msgs":["No input files"]}]}' >&2
exit 1
`,
		)
		r = run(&p, "compiler failure with warning-only JSON", 1, compiler = fake)
		has_error := false
		for violation in r.violations {has_error ||= violation.severity == "error"}
		probe.expect(
			&p,
			!r.coverage.complete && has_status(r, "failed") && has_error,
			"warning-only compiler failure remains an error",
		)
		probe.write(fake, "#!/bin/sh\necho compiler-unavailable >&2\nexit 7\n")
		baseline := fmt.tprintf("%s/odx.baseline", root)
		baseline_text :: `{"format_version":2,"entries":[{"rule":"probe/R1","file":"lib/lib.odin","subject":"old-subject","line":1,"col":1,"fingerprint":"0000000000000000000000000000000000000000000000000000000000000000","reason":"existing debt"}]}`
		probe.write(baseline, baseline_text)
		r = run(&p, "compiler failure without JSON", 2, compiler = fake)
		probe.expect(
			&p,
			!r.coverage.complete && has_status(r, "failed") && len(r.tool_errors) > 0,
			"compiler process failure: tool error",
		)
		data, err := os.read_entire_file(baseline, context.allocator)
		probe.expect(
			&p,
			err == nil && string(data) == baseline_text,
			"unavailable evidence preserves baseline bytes",
		)
		probe.run_cli(&p, "baseline regen unavailable evidence", 2, {"baseline", "regen"}, fake)
		data, err = os.read_entire_file(baseline, context.allocator)
		probe.expect(
			&p,
			err == nil && string(data) == baseline_text,
			"failed baseline regeneration preserves baseline bytes",
		)
	} else {
		fmt.println("SKIP fake-compiler failure cases: Unix shell wrappers unavailable on Windows")
	}

	p.root = "tests/fixtures/contract"
	r = run(&p, "scoped dependency graph", 1, {"--topic", "dependencies", "dependencies_r2_via"})
	probe.expect(
		&p,
		r.coverage.complete && !has_status(r, "unsupported") && len(r.violations) > 0,
		"scoped dependency graph: complete graph produces finding",
	)
	p.root = root
	command("git", "-C", root, "init", "-q")
	command("git", "-C", root, "add", ".")
	command(
		"git",
		"-C",
		root,
		"-c",
		"user.name=odx probe",
		"-c",
		"user.email=probe@example.invalid",
		"-c",
		"commit.gpgsign=false",
		"commit",
		"-qm",
		"probe",
	)
	r = run(&p, "unchanged since HEAD", 0, {"--since", "HEAD"})
	probe.expect(
		&p,
		r.coverage.selection == "since" && !r.coverage.complete && len(r.coverage.packages) == 0,
		"unchanged since HEAD: empty selection, no whole-project claim",
	)
	for invalid in ([]bool{false, true}) {
		if invalid {probe.write(config_path, "{ broken config")} else {os.remove(config_path)}
		out, errors := probe.run_cli(&p, "project loading JSON failure", 2, {"check", "--json"})
		failure: probe.Report
		err := json.unmarshal_string(out, &failure)
		probe.expect(
			&p,
			err == nil &&
			len(failure.tool_errors) > 0 &&
			!failure.coverage.complete &&
			errors == "",
			"missing or invalid config is a structured tool failure",
		)
	}
	checklist_config, _ := strings.replace_all(config, "roles: {}", `roles: {pure: ["lib"]}`)
	probe.write(config_path, checklist_config)
	checklist, _ := probe.run_cli(
		&p,
		"structured checklist",
		0,
		{"policy", "--topic", "errors", "--checklist", "--json"},
	)
	advice: struct {
		advice: []struct {
			topic, advice: string,
		},
	}
	advice_err := json.unmarshal_string(checklist, &advice)
	probe.expect(
		&p,
		advice_err == nil &&
		len(advice.advice) == 1 &&
		advice.advice[0].topic == "errors" &&
		advice.advice[0].advice != "",
		"checklist is machine-readable",
	)
}
