package milestone_probe

import "core:encoding/json"
import "core:fmt"
import "core:os"
import "core:path/filepath"
import "core:strings"

Check :: struct {
	package_dir, rule, evidence, boundary, status, reason: string,
	findings:                                              int,
}

Report :: struct {
	tool_errors: []string,
	violations:  []struct {
		rule, message, severity: string,
	},
	coverage:    struct {
		selection, source_scope, compiler_scope: string,
		complete:                                bool,
		packages:                                []struct {
			package_dir: string,
			files:       []string,
		},
		checks:                                  []Check,
	},
}

Probe :: struct {
	bin, root:      string,
	passed, failed: int,
}

write :: proc(path, text: string) {
	err := os.make_directory_all(filepath.dir(path))
	if err != nil && err != os.General_Error.Exist {panic(fmt.tprintf("%v", err))}
	if err = os.write_entire_file(path, text); err != nil {panic(fmt.tprintf("%v", err))}
}

expect :: proc(p: ^Probe, ok: bool, name: string) {
	if ok {
		p.passed += 1
		fmt.printfln("PASS %s", name)
	} else {
		p.failed += 1
		fmt.printfln("FAIL %s", name)
	}
}

run :: proc(
	p: ^Probe,
	name: string,
	expected_exit: int,
	args: []string = nil,
	compiler := "",
) -> Report {
	cmd := make([dynamic]string)
	append(&cmd, "check", "--json")
	append(&cmd, ..args)
	stdout, _ := run_cli(p, name, expected_exit, cmd[:], compiler)
	r: Report
	jerr := json.unmarshal(transmute([]u8)stdout, &r)
	expect(
		p,
		jerr == nil && r.coverage.source_scope != "",
		fmt.tprintf("%s: valid JSON with coverage", name),
	)
	return r
}

run_cli :: proc(
	p: ^Probe,
	name: string,
	expected_exit: int,
	args: []string,
	compiler := "",
) -> (
	out, errors: string,
) {
	cmd := make([dynamic]string)
	append(&cmd, p.bin)
	append(&cmd, ..args)
	append(&cmd, "--root", p.root)
	env: [dynamic]string
	if compiler != "" {
		inherited, env_err := os.environ(context.allocator)
		if env_err != nil {panic(fmt.tprintf("%v", env_err))}
		for entry in inherited {
			if !strings.has_prefix(entry, "ODX_ODIN=") {append(&env, entry)}
		}
		append(&env, fmt.tprintf("ODX_ODIN=%s", compiler))
	}
	state, stdout, stderr, err := os.process_exec(
		{command = cmd[:], env = env[:]},
		context.allocator,
	)
	expect(
		p,
		err == nil && state.exit_code == expected_exit,
		fmt.tprintf("%s: exit %d (got %d, %v)", name, expected_exit, state.exit_code, err),
	)
	if err != nil ||
	   state.exit_code != expected_exit {fmt.printfln("stdout: %s\nstderr: %s", stdout, stderr)}
	return string(stdout), string(stderr)
}

has_status :: proc(r: Report, status: string) -> bool {
	for check in r.coverage.checks {if check.status == status {return true}}
	return false
}

command :: proc(args: ..string) {
	state, stdout, stderr, err := os.process_exec({command = args}, context.allocator)
	if err != nil ||
	   state.exit_code != 0 {panic(fmt.tprintf("%v: %v\n%s\n%s", args, err, stdout, stderr))}
}

// Freshly build odx, then run this file from the repository root with ODX_ODIN set.
main :: proc() {
	context.allocator = context.temp_allocator
	defer free_all(context.temp_allocator)
	odin := os.get_env("ODX_ODIN", context.allocator)
	if odin == "" ||
	   !filepath.is_abs(odin) {panic("set ODX_ODIN to the reference compiler's absolute path")}
	bin, berr := filepath.abs("build/odx")
	if berr != nil {panic(fmt.tprintf("%v", berr))}
	root, terr := os.make_directory_temp("", "odx-m1-*", context.allocator)
	if terr != nil {panic(fmt.tprintf("%v", terr))}
	defer os.remove_all(root)
	p := Probe {
		bin  = bin,
		root = root,
	}
	config :: `{
 version: 1, roles: {},
 exclude: ["excluded/**", ".odx/**"],
 odin: {flags: [], explicit_allocators: "off"},
}`
	config_path := fmt.tprintf("%s/odx.json5", root)
	write(config_path, config)
	source := fmt.tprintf("%s/lib/lib.odin", root)
	write(source, "package lib\nanswer :: 42\n")
	r := run(&p, "full clean", 0)
	expect(&p, r.coverage.complete && has_status(r, "complete"), "full clean: completed evidence")
	platform := "windows" if ODIN_OS != .Windows else "linux"
	platform_file := fmt.tprintf("lib/inactive_%s.odin", platform)
	write(
		fmt.tprintf("%s/%s", root, platform_file),
		"package lib\nplatform_value :: undeclared_on_active_target\n",
	)
	write(
		fmt.tprintf("%s/lib/generated.odin", root),
		"// Code generated by the evidence probe. DO NOT EDIT.\npackage lib\ngenerated_value :: 7\n",
	)
	write(
		fmt.tprintf("%s/lib/example_test.odin", root),
		"package lib\nimport \"core:testing\"\n@(test)\nexample :: proc(t: ^testing.T) {}\n",
	)
	write(
		fmt.tprintf("%s/lib/conditional.odin", root),
		"package lib\nwhen false { inactive_value :: undeclared_in_inactive_branch }\n",
	)
	write(fmt.tprintf("%s/excluded/broken/bad.odin", root), "not valid Odin\n")
	r = run(&p, "source coverage", 0)
	files := make(map[string]bool)
	for pkg in r.coverage.packages {for file in pkg.files {files[file] = true}}
	expect(
		&p,
		r.coverage.complete && len(r.coverage.packages) == 1 && len(files) == 5,
		"source coverage: only included package files",
	)
	for file in ([]string{platform_file, "lib/generated.odin", "lib/example_test.odin", "lib/conditional.odin"}) {
		expect(&p, files[file], fmt.tprintf("source coverage includes %s", file))
	}
	r = run(&p, "fast", 0, {"--fast"})
	expect(
		&p,
		!r.coverage.complete && has_status(r, "skipped"),
		"fast: compiler evidence explicitly skipped",
	)
	write(source, "answer :: 42\n")
	r = run(&p, "missing package", 1)
	expect(
		&p,
		!r.coverage.complete && len(r.violations) > 0,
		"missing package: diagnostic and incomplete coverage",
	)
	_, trial_errors := run_cli(
		&p,
		"rule trial malformed source",
		1,
		{"rule", "try", `{kind:"pattern",match:"decl",at:"package_scope",mutable:true}`},
	)
	expect(
		&p,
		strings.contains(trial_errors, "failed"),
		"rule trial malformed source: failure disclosed",
	)
	write(
		config_path,
		`{
 version: 1, roles: {},
 exclude: ["excluded/**", ".odx/**"],
 odin: {flags: [], explicit_allocators: "off", allowed_vet_disables: ["unused"]},
}`,
	)
	write(source, "#+vet !unused\npackage lib\nbroken :: proc(\n")
	r = run(&p, "malformed source with allowed vet disable", 1)
	stale := false
	for violation in r.violations {stale ||= violation.rule == "odx/stale-config-entry"}
	expect(
		&p,
		!r.coverage.complete && !stale,
		"failed syntax does not falsely report vet allowance as stale",
	)
	write(config_path, config)
	write(source, "package lib\nanswer: int = \"wrong type\"\n")
	r = run(&p, "compiler source error", 1)
	expect(
		&p,
		!r.coverage.complete && has_status(r, "failed") && len(r.violations) > 0,
		"compiler source error: failed evidence and diagnostics",
	)
	hook_output, _ := run_cli(&p, "hook compiler error", 0, {"hook", "edit"})
	expect(
		&p,
		strings.contains(hook_output, "source rules were not executed"),
		"hook compiler error: source rules explicitly skipped",
	)
	write(source, "package lib\nanswer :: 42\n")

	when ODIN_OS != .Windows {
		fake := fmt.tprintf("%s/fake-odin", root)
		write(fake, "#!/bin/sh\nexit 0\n")
		if err := os.chmod(fake, os.Permissions{.Read_User, .Write_User, .Execute_User});
		   err != nil {panic(fmt.tprintf("%v", err))}
		// Exported-procedure checks demand doc evidence even when this example has no violations.
		write(
			fmt.tprintf("%s/.odx/topics/probe/topic.md", root),
			`---
name: "probe",
summary: "Compiler evidence probe",
---
Probe.
`,
		)
		write(
			fmt.tprintf("%s/.odx/topics/probe/R1.odx.md", root),
			`---
id: "R1",
statement: "Fallible exported procedures require results",
why: "Do not silently discard failure",
instead_of: "Discarding failures",
evidence: "Compiler entity facts",
cost: "Compiler doc",
severity: "error",
check: {kind: "require_attribute", attribute: "require_results", on: "exported_procs"},
---
Probe.
`,
		)
		r = run(&p, "success without doc output", 2, compiler = fake)
		expect(
			&p,
			!r.coverage.complete && has_status(r, "failed") && len(r.tool_errors) > 0,
			"missing doc output: unavailable evidence",
		)
		_, doc_errors := run_cli(
			&p,
			"rule trial absent doc export",
			2,
			{
				"rule",
				"try",
				`{kind:"require_attribute",attribute:"require_results",on:"exported_procs"}`,
			},
			fake,
		)
		expect(
			&p,
			strings.contains(doc_errors, "failed"),
			"rule trial absent doc export: failure disclosed",
		)
		write(fake, "#!/bin/sh\nif [ \"$1\" = doc ]; then exit 7; fi\nexit 0\n")
		r = run(&p, "doc process failure", 2, compiler = fake)
		expect(
			&p,
			!r.coverage.complete && has_status(r, "failed"),
			"doc process failure: failed evidence",
		)
		write(
			fake,
			`#!/bin/sh
echo '{"error_count":1,"errors":[{"type":"warning","pos":null,"msgs":["No input files"]}]}' >&2
exit 1
`,
		)
		r = run(&p, "compiler failure with warning-only JSON", 1, compiler = fake)
		has_error := false
		for violation in r.violations {has_error ||= violation.severity == "error"}
		expect(
			&p,
			!r.coverage.complete && has_status(r, "failed") && has_error,
			"warning-only compiler failure remains an error",
		)
		write(fake, "#!/bin/sh\necho compiler-unavailable >&2\nexit 7\n")
		baseline := fmt.tprintf("%s/odx.baseline", root)
		baseline_text :: "format_version: 1\nprobe/R1\tlib\told-subject\n"
		write(baseline, baseline_text)
		r = run(&p, "compiler failure without JSON", 2, compiler = fake)
		expect(
			&p,
			!r.coverage.complete && has_status(r, "failed") && len(r.tool_errors) > 0,
			"compiler process failure: tool error",
		)
		data, err := os.read_entire_file(baseline, context.allocator)
		expect(
			&p,
			err == nil && string(data) == baseline_text,
			"unavailable evidence preserves baseline bytes",
		)
		run_cli(&p, "baseline regen unavailable evidence", 2, {"baseline", "regen"}, fake)
		data, err = os.read_entire_file(baseline, context.allocator)
		expect(
			&p,
			err == nil && string(data) == baseline_text,
			"failed baseline regeneration preserves baseline bytes",
		)
	} else {
		fmt.println("SKIP fake-compiler failure cases: Unix shell wrappers unavailable on Windows")
	}

	p.root = "tests/fixtures/contract"
	r = run(
		&p,
		"scoped dependency graph",
		2,
		{"--ci", "--topic", "dependencies", "dependencies_r2_via"},
	)
	expect(
		&p,
		!r.coverage.complete && has_status(r, "unsupported"),
		"scoped dependency graph: incomplete graph disclosed",
	)
	p.root = root
	command("git", "-C", root, "init", "-q")
	command("git", "-C", root, "add", ".")
	command(
		"git",
		"-C",
		root,
		"-c",
		"user.name=odx probe",
		"-c",
		"user.email=probe@example.invalid",
		"-c",
		"commit.gpgsign=false",
		"commit",
		"-qm",
		"probe",
	)
	r = run(&p, "unchanged since HEAD", 0, {"--since", "HEAD"})
	expect(
		&p,
		r.coverage.selection == "since" && !r.coverage.complete && len(r.coverage.packages) == 0,
		"unchanged since HEAD: empty selection, no whole-project claim",
	)
	fmt.printfln("Milestone 1 probe: %d passed, %d failed", p.passed, p.failed)
	if p.failed != 0 {os.exit(1)}
}
